### ISSUE TITLE
channelId not set dynamically

### ISSUE THREAD

**Issue by mr-smithers-excellent** [FirebaseExtended/action-hosting-deploy#10]
First off, love the potential of this action and I'm happy to contribute where help is needed.

On the latest Alpha release, although the docs state `If you don't set it, a new channel will be created per-PR or per-branch`, I receive the following error with leaving `channelId` blank:

```
  /home/runner/work/my-repo/my-repo/node_modules/.bin/firebase hosting:channel:deploy  --project my-project --json
  ***
    "status": "error",
    "error": "channelID is currently required"
  ***
  ***
    "status": "error",
    "error": "channelID is currently required"
  ***
```

**Comment by jhuleatt** [comment]
Hi @mr-smithers-excellent! Can you please post your workflow yml file? The auto-channelId does work ([example](https://github.com/FirebaseExtended/action-hosting-deploy/pull/14#issuecomment-689722457)) for PRs.

**Comment by mr-smithers-excellent** [comment]
@jhuleatt - I can confirm this is working as expected. My mistake, I was originally pushing to a feature branch prior to opening a PR. Once I opened the PR, the `channelId` populated as expected. Closing!
