### ISSUE TITLE
Add deployed URL as an output

### ISSUE THREAD

**Issue by mr-smithers-excellent** [FirebaseExtended/action-hosting-deploy#11]
Feature request - add GH Actions output that contains the deployed Firebase URL

**Comment by jhuleatt** [comment]
Looks like the action does set the URL as an output for a preview deploy: https://github.com/FirebaseExtended/action-hosting-deploy/blob/29b1863143013b8b2251e7d66381f798db93266f/src/index.ts#L102-L104

But not for the production deploy, so we should add that. Thanks @mr-smithers-excellent for the request!

**Comment by mr-smithers-excellent** [comment]
@jhuleatt - ahh ok, that's good news! They should also be added to the `action.yml` file ([docs link](https://docs.github.com/en/actions/creating-actions/metadata-syntax-for-github-actions#outputs)) and the `README`. Looks like only the inputs are documented right now.

**Comment by jhuleatt** [comment]
Thanks for the information! I've started a PR and would be interested to get your feedback on it

**Comment by mr-smithers-excellent** [comment]
Looks good to me, that would certainly close this issue from my perspective.
