### ISSUE TITLE
Specify `message` for each deployment

### ISSUE THREAD

**Issue by mathiasbynens** [FirebaseExtended/action-hosting-deploy#12]
It would be amazing if this action would specify a build stamp for each deployment, similar to how you’d manually do:

```
firebase deploy --message "Deploy @ ${COMMIT_HASH}";
```

For deploy previews, the message could be something like:

```
firebase deploy --message "Deploy preview for PR #${PR_ID} @ ${COMMIT_HASH}";
```

This way, the Firebase Hosting dashboard always clearly shows which PR or merged commit each deployment corresponds to.

**Comment by jhuleatt** [comment]
TIL about the `--message` flag! Thanks for the suggestion!

Based on some quick testing, it looks like this is only supported for `firebase deploy`, not `firebase hosting:channel:deploy`, but will look into this further

**Comment by jhuleatt** [comment]
After looking, I'm not sure if this is supported on the backend. I've filed a feature request with the Hosting team internally to explore this.
