### ISSUE TITLE
[BUG] Deploys for build folder display a white screen (website with no content)

### ISSUE THREAD

**Issue by 123MwanjeMike** [FirebaseExtended/action-hosting-deploy#131]
### Action config 
.github/workflows/firebase-hosting-pull-request.yml
>name: Deploy to Firebase Hosting on PR
'on': pull_request
jobs:
&nbsp;&nbsp;build_and_preview:
&nbsp;&nbsp;&nbsp;&nbsp;if: '${{ github.event.pull_request.head.repo.full_name == github.repository }}'
&nbsp;&nbsp;&nbsp;&nbsp;runs-on: ubuntu-latest
&nbsp;&nbsp;&nbsp;&nbsp;steps:
&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;- uses: actions/checkout@v2
&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;- run: rm -rf node_modules && yarn install --frozen-lockfile && yarn build
&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;- uses: FirebaseExtended/action-hosting-deploy@v0
&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;with:
&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;repoToken: '${{ secrets.GITHUB_TOKEN }}'
&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;firebaseServiceAccount: '${{ secrets.FIREBASE_SERVICE_ACCOUNT_PROJECT_ID }}'
&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;projectId: PROJECT_ID
&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;entryPoint: ./

.firebase.json
>{
&nbsp;&nbsp;"hosting": {
&nbsp;&nbsp;&nbsp;&nbsp;"public": "build",
&nbsp;&nbsp;&nbsp;&nbsp;"ignore": [
&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;"firebase.json",
&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;"**/.*",
&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;"**/node_modules/**"
&nbsp;&nbsp;&nbsp;&nbsp;],
&nbsp;&nbsp;&nbsp;&nbsp;"rewrites": [
&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;{
&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;"source": "**",
&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;"destination": "/index.html"
&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;}
&nbsp;&nbsp;&nbsp;&nbsp;]
&nbsp;&nbsp;}
}

### Error message
No error message is given

### Expected behavior
Website at preview URL with web content

### Actual behavior
Website at preview URL is a blank white screen without any web content

**Note:** PROJECT_ID is not a variable, it's a place holder for my project ID

**Comment by 123MwanjeMike** [comment]
PROJECT_ID is not a variable, it's a place holder for my project ID

**Comment by 123MwanjeMike** [comment]
After more analysis, I figured that this error seems not to occur if a pre built folder is pushed to remote unlike when built by the `- run: rm -rf node_modules && yarn install --frozen-lockfile && yarn build` step

**Comment by jhuleatt** [comment]
@123MwanjeMike do you see anything in the JS console when you load the preview URL in your browser? Does the HTML look like you'd expect? I ask because if Firebase Hosting is serving anything besides a 404 error page, my guess is that this is a bug in your app, and not an issue with the GitHub action.

**Comment by 123MwanjeMike** [comment]
I figured it was a problem with how my <App > component was being rendered, and not a bug with the action itself
