### ISSUE TITLE
[BUG] Firebase Hosting "Number of releases to keep" is ignored when deployment is via Github actions

### ISSUE THREAD

**Issue by chrisjacobs91** [FirebaseExtended/action-hosting-deploy#175]
### Error message
I have Firebase Hosting setup from the Firebase Console to only keep the latest 4 deployments. This works fine when I deploy from the CLI, however deployments made via the GitHub Action don't seem to trigger this behaviour and now I have a LOT of deployments.

Is there something I can add to the Action or is this a bug that needs fixing on Firebase side?

### Expected behavior
The maximum number of deployments set in the Firebase Console website is respected when deploying via Github Actions

### Actual behavior
It isn't.

**Comment by bkendall** [comment]
Is this still occurring? It's not going to be "GH action specific" but it's going to be something on the server-side. If it is happening, can you reach out to Firebase Support directly? We can look into your project and figure out what's happening.
