### ISSUE TITLE
[BUG] Please release new version to fix #55

### ISSUE THREAD

**Issue by anisabboud** [FirebaseExtended/action-hosting-deploy#233]
Hi, I ran into this exact issue: https://github.com/FirebaseExtended/action-hosting-deploy/issues/55.

Which was already fixed https://github.com/FirebaseExtended/action-hosting-deploy/commit/e2fe962f2f8103450d338d90e4837bd376527d40 in Dec 2020.
However, the [latest release](https://github.com/FirebaseExtended/action-hosting-deploy/releases) is from Aug 2020.

Can you please release an updated version of this plugin? Thanks!

**Comment by bkendall** [comment]
We've just released a new version (and updated the v0 tag), so this should be addressed!
