### ISSUE TITLE
[BUG] Cannot Find Module "is-npm"

### ISSUE THREAD

**Issue by brian-cresicor** [FirebaseExtended/action-hosting-deploy#235]
### Error message

![image](https://user-images.githubusercontent.com/95242222/191920559-afc6e795-d676-4399-8700-47b025c91f71.png)

### Expected behavior

Deployment completes successfully.

### Actual behavior

Deployment fails due to missing module `is-npm` in `firebase-tools`.

**Comment by vigneshwaran-vtpl** [comment]
+1

**Comment by UgniusSmidtas** [comment]
Same here :/

**Comment by emrahyumuk** [comment]
+1

**Comment by ocruzv** [comment]
This error comes from the firebase/firebase-tools dependency. I think that will be solved on a future update on their end https://github.com/firebase/firebase-tools/issues/5010

**Comment by emrahyumuk** [comment]
> This error comes from the firebase/firebase-tools dependency. I think that will be solved on a future update on their end [firebase/firebase-tools#5010](https://github.com/firebase/firebase-tools/issues/5010)

There is no problem with firebase-tools on local. I just get this error on github action

**Comment by aliak00** [comment]
Same here. How could this start happening with no code changes or dep changes? Is there some funny config somewhere? I can see `is-npm` in my package lock file. - we are on firebase-tools version 10.7.0. Updating that didn't help.

**Comment by Maria-Lurdes** [comment]
I have the same issue, updated everything in my project but it didn't help

**Comment by bkendall** [comment]
Thanks for reporting. We've got a couple people looking into this trying to figure out what happened. So far as we can tell, locally deploying should work fine and it's just the GH action that's broken (which is only more confusing).

**Comment by aliak00** [comment]
FYI @bkendall : Changed github action to use node 16 instead of 14 and it all good 🤷 

<img width="1243" alt="image" src="https://user-images.githubusercontent.com/2638284/192094850-15dbf7e2-c165-4ded-a8b5-1ad878676c77.png">

**Comment by gorden0929** [comment]
+1

**Comment by elmehdibm** [comment]
Same here

**Comment by serhatpubinno** [comment]
> FYI @bkendall : Changed github action to use node 16 instead of 14 and it all good 🤷
> 
> <img alt="image" width="1243" src="https://user-images.githubusercontent.com/2638284/192094850-15dbf7e2-c165-4ded-a8b5-1ad878676c77.png">

its work for me

**Comment by Jerkovic** [comment]
+1

**Comment by rafaelkorz** [comment]
+ 1

**Comment by igorgottschalg** [comment]
+1

**Comment by bkendall** [comment]
Alright, we've at least made a little patch in the code we think is triggering the error to catch it and be a little more quiet if this happens. We're still digging into _why_ this is happening, but planning on releasing tomorrow morning with that patch.

**Comment by bkendall** [comment]
This is the patch we made, fwiw: firebase/firebase-tools#5010

**Comment by dawogfather** [comment]
+1 👍🏽

**Comment by AntiraLoachote** [comment]
+1

**Comment by dcroote** [comment]
Working now, thanks!

**Comment by victorwvieira** [comment]
It's working now, thank you!
