### ISSUE TITLE
Pin version of firebase-tools used for deploys.

### ISSUE THREAD

**Issue by mikelehen** [FirebaseExtended/action-hosting-deploy#242]
### The use case you're trying to solve

Github deploys work reliably from day to day.

### Change to the action that would solve that use case

Instead of installing the latest firebese-tools every time, pin to a version that is known to work correctly and only update it periodically.  Perhaps allow developers to override the version if they choose.

### Other considerations

For context, the firebase-tools@11.14.0 release had a regression that broke deploys for many firebase projects. https://github.com/firebase/firebase-tools/issues/5071

I don't need my automatic deploys to be using the absolute latest version of firebase-tools.  I'd rather it only update occasionally so that I'm not subject to surprise breakages.

**Comment by aaronadamsCA** [comment]
+1 to pinning the dependency. I know it would require an action release every time the internal version was to be updated; but this would be correct, and would mirror the way other GitHub Actions generally work.

**Comment by drummerjolev** [comment]
+1, great idea @mikelehen

**Comment by mikelehen** [comment]
Awesome, thanks @davideast!

**Comment by jhuleatt** [comment]
Thanks for the feedback all! `firebaseToolsVersion` is now available [as an option](https://github.com/FirebaseExtended/action-hosting-deploy#firebasetoolsversion-string) thanks to #246. For now, we're going to keep `@latest` as the default behavior.
