### ISSUE TITLE
Upgrade current action to use node 16 instead of 12

### ISSUE THREAD

**Issue by soleo** [FirebaseExtended/action-hosting-deploy#244]
### The use case you're trying to solve
Node.js 12 actions are deprecated. For more information see: https://github.blog/changelog/2022-09-22-github-actions-all-actions-will-begin-running-on-node16-instead-of-node12/. Please update the following actions to use Node.js 16: actions/checkout,  FirebaseExtended/action-hosting-deploy, actions/checkout

### Change to the action that would solve that use case

- Upgrade to node 16
- Update documentation

**Comment by soleo** [comment]
https://github.com/FirebaseExtended/action-hosting-deploy/pull/245/files for the changes

**Comment by angelcervera** [comment]
Is this fixed? If so, what is the right way to use it? The firebase init is still creating a wrong GitHub Action.

**Comment by oyvindwe** [comment]
This issue seems to be fixed (partially) by PR #246, but now v16 is deprecated, and actions must be updated to use node v20 per https://github.blog/changelog/2023-09-22-github-actions-transitioning-from-node-16-to-node-20/

**Comment by jhuleatt** [comment]
Fixed by #344 https://github.com/FirebaseExtended/action-hosting-deploy/pull/344
