### ISSUE TITLE
Output `firebase-tools` version during execution

### ISSUE THREAD

**Issue by jthegedus** [FirebaseExtended/action-hosting-deploy#27]
Since `firebase-tools` is executed with `npx` the specific Firebase CLI version used is unknown. This would be useful information to output during execution for easier debugging.

`npx` **should** use the `latest` available on `npm`, but when debugging issues **knowing** this information is crucial.

**Comment by bkendall** [comment]
npx does output the version, which is nice. e.g. `npm WARN exec The following package was not found and will be installed: firebase-tools@11.14.0`.

You can also now pin the version of firebase tools. Hope that helps!
