### ISSUE TITLE
Node.js 16 actions are deprecated

### ISSUE THREAD

**Issue by rohit231095** [FirebaseExtended/action-hosting-deploy#341]
I am seeing this below warning in my project's GitHub actions repeatedly. This Firebase deployment action needs an upgrade to Node.js 18 or 20 as version 16 actions are deprecated.

> Node.js 16 actions are deprecated. Please update the following actions to use Node.js 20: FirebaseExtended/action-hosting-deploy@v0. For more information see: https://github.blog/changelog/2023-09-22-github-actions-transitioning-from-node-16-to-node-20/.

Please upgrade this action as soon as possible.

**Comment by MNITD** [comment]
@rohit231095 do you have only the warning in the console or the action is broken as well?

**Comment by rohit231095** [comment]
@MNITD I can see only a warning like the image below. The action is still working, and deployment is not broken.

![image](https://github.com/FirebaseExtended/action-hosting-deploy/assets/47350759/d5cb3c7a-560e-4672-95f6-3a47dd7dfef2)

Reporting it to prevent any incoming breaking possibilities later on.

**Comment by oyvindwe** [comment]
I have already submitted PR #340 to address this.

Would be good if some of the maintainers could follow up before Node 16 is sunset!

**Comment by annoyingmouse** [comment]
Actions are now failing:

![image](https://github.com/FirebaseExtended/action-hosting-deploy/assets/1125148/5803ad81-31e7-4926-ab8c-a7d11a151a2e)

**Comment by oyvindwe** [comment]
> Actions are now failing:

That is most likely some other problem with your job. Sunset date for node 16 has not yet been communicated.

**Comment by annoyingmouse** [comment]
> > Actions are now failing:
> 
> That is most likely some other problem with your job. Sunset date for node 16 has not yet been communicated.

You are right - please accept my apologies!

**Comment by filfreire** [comment]
FYI, while maintainers don't merge @oyvindwe's PR #340 that fixes this warning, you can edit your action usage to point to the PR's commit directly:
```diff
-FirebaseExtended/action-hosting-deploy@v0
+FirebaseExtended/action-hosting-deploy@79b1a830a9ae85409cb38056dd7761f6f1cb83fd
```

**Comment by johnnyoshika** [comment]
This workaround to set a node version doesn't work:

```
      - uses: actions/setup-node@v4
        with:
          node-version: '18'
```

When using `FirebaseExtended/action-hosting-deploy@v0` I still get this warning:

```
Node.js 16 actions are deprecated. Please update the following actions to use Node.js 20: FirebaseExtended/action-hosting-deploy@v0. For more information see: https://github.blog/changelog/2023-09-22-github-actions-transitioning-from-node-16-to-node-20/.
```

**Comment by steve-scorn** [comment]
This appears to have now been enforced, making this action no longer usable.

The only way I could get it to work was by using @filfreire 's solution above. Is it possible to get PR #340 merged?

**Comment by oyvindwe** [comment]
@johnnyoshika 
> This workaround to set a node version doesn't work:

This is to set the node version your build uses, not the version used by the action itself.

@steve-scorn:
> This appears to have now been enforced, making this action no longer usable.

According to https://github.blog/changelog/2024-03-07-github-actions-all-actions-will-run-on-node20-instead-of-node16-by-default/
> [GitHub] will start enforcing the use of Node20 rather than Node16 on the 13th of May.

**Comment by testak-m** [comment]
I asked if it would be possible to release #344 since it would be resolved once it was released.
https://github.com/FirebaseExtended/action-hosting-deploy/pull/344#issuecomment-1986804951

**Comment by jhonnycgarcia** [comment]
The error is still occurring.
![image](https://github.com/FirebaseExtended/action-hosting-deploy/assets/19494854/213e0725-23f4-4d03-89e0-0d6784f7179f)

**Comment by oyvindwe** [comment]
> The error is still occurring.

It will occur until a fix is merged and released.

Workaround is described here: https://github.com/FirebaseExtended/action-hosting-deploy/issues/341#issuecomment-1952388122

**Comment by wayzie-jm** [comment]
I'm still having this issue.  Are there any changes needed in the yml?

`name: Deploy to Firebase Hosting on merge
on:
  push:
    branches:
      - main
jobs:
  build_and_deploy:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - run: npm ci && npm run build
      - uses: FirebaseExtended/action-hosting-deploy@v0
        with:
          repoToken: ${{ secrets.GITHUB_TOKEN }}
          firebaseServiceAccount: ${{ secrets.FIREBASE_SERVICE_ACCOUNT_XXXXX}}
          channelId: live`

**Comment by memark** [comment]
@wayzie-jm AFAICT the fix has only been merged, not released.

**Comment by wayzie-jm** [comment]
> @wayzie-jm AFAICT the fix has only been merged, not released.

Rookie mistake.  Thanks.

**Comment by Danish-Dsouza** [comment]
What does one have to do to get a release around here?
