### ISSUE TITLE
[ENHANCEMENT] Disable auto-commenting to PR for matrix jobs

### ISSUE THREAD

**Issue by weilinzung** [FirebaseExtended/action-hosting-deploy#356]
### The use case you're trying to solve

When using this action for matrix jobs, it will post multiple PR comments. Like 10x deploy matrix jobs, it will post 10x of PR comments.

### Change to the action that would solve that use case

- Add new input to disable auto-commenting
- Add deployed metadata to the action output, like the preview URL and expired date

### Other considerations

Once we can disable the auto-commenting and have the outputs(metadata), we would like to post the comment once with all the deploy preview channel links.

**Comment by jhuleatt** [comment]
Fixed in #371
