### ISSUE TITLE
firebase init hosting:github stuck on 'authentication...'

### ISSUE THREAD

**Issue by aviTwito** [FirebaseExtended/action-hosting-deploy#37]
Using firebase cli version 8.12.1
I have existing project with hosting configured
Steps:
1. ran the command `firebase init hosting:github`  to configure the new feature of github action
2. Browser opened to authenticate github account
3. After press on allow permission on github page, redirected to a url like:  'http://localhost:9005/?code< Some Hash Code >=<some hash>&state=1055088609'
4. Response from url: This site can’t be reached. localhost refused to connect.
5. firebase cli is in state 'Waiting for authentication...'
6. After ctrl+c the command, and re-running it, And pressing on the link at the shell
   https://github.com/login/oauth/authorize?client_id=< Some Hash Code >&redirect_uri=http%3A%2F%2Flocalhost%3A9005&scope=read%3Auser%20repo%20public_repo''
broswser is imeedietly redirected to the redirect url at step 3, Without going through grant permission again

**Comment by jhuleatt** [comment]
@aviTwito that's very strange! If you encounter this again, can you please file it in the https://github.com/firebase/firebase-tools repository? That's where the `firebase init hosting:github` source lives.
