### ISSUE TITLE
Please try again in 30 seconds.

### ISSUE THREAD

**Issue by AsimNet** [FirebaseExtended/action-hosting-deploy#43]
Hey,
I used firebase-tools to set-up the github action.
but i'm getting this error:
```
<p><b>502.</b> <ins>That’s an error.</ins>
<p>The server encountered a temporary error and could not complete your request.<p>Please try again in 30 seconds.  <ins>That’s all we know.</ins>
```
is there a status page to follow?
or this error because of something I did from my end (permission error in Gcloud or something)

**Comment by jhuleatt** [comment]
@AsimNet can you please add some more context so that I can help?

Does this error come from firebase-tools when you set up the action, or from the action when it runs? Any more details about what triggers the error?

**Comment by AsimNet** [comment]
Hey @jhuleatt,
this error occurs when the action run.

![image](https://user-images.githubusercontent.com/3624441/96653532-fa6a3b00-1341-11eb-8701-74e8c87052db.png)

![image](https://user-images.githubusercontent.com/3624441/96653591-1c63bd80-1342-11eb-9a2e-bd19521f8f3e.png)

**Comment by jhuleatt** [comment]
Thanks @AsimNet! Looks like it's the same issue that's discussed in https://github.com/FirebaseExtended/action-hosting-deploy/issues/45, so I'm going to close this out. Take a look at https://github.com/FirebaseExtended/action-hosting-deploy/issues/45#issuecomment-717838006 for a workaround while we roll out a fix on the Hosting backend.
