### ISSUE TITLE
Support multiple projects

### ISSUE THREAD

**Issue by mr-bjerre** [FirebaseExtended/action-hosting-deploy#44]
Thank you for this action first of all. I have multiple projects, e.g. one for staging and one for production. It would be nice if that was supported by this action - service accounts etc. are needed

**Comment by jhuleatt** [comment]
@mr-bjerre thanks for the feedback! This action does let you configure [project id](https://github.com/FirebaseExtended/action-hosting-deploy#projectid-string), so this shouldn't be a problem. You can create one workflow .yaml file that listens to GitHub events that you'd want to deploy to your staging project on, and a different workflow .yaml to deploy to your production project. You can upload different service account keys as different secrets in your repo, and reference them from your workflow .yaml files.

Does that fit your use case? Any suggestions on how we can improve the action or our docs to make things easier?

**Comment by mr-bjerre** [comment]
That sounds very straightforward. I used `firebase init` and set it up that way. Very easy - it would be cool with an option to set up multiple firebase projects through that. I realize that's a `firebase` issue rather!

Btw. I also have to deploy firestore rules and cloud functions. Do you plan to integrate that as well? I'd think it requires minimal effort

**Comment by jhuleatt** [comment]
@mr-bjerre since Hosting is the only product that supports this "preview channels" functionality, this action is just focused on Hosting. We are looking into creating other actions in the future, though!
