### ISSUE TITLE
Static subdomain

### ISSUE THREAD

**Issue by rthreei** [FirebaseExtended/action-hosting-deploy#58]
When deploying to a new preview channel for every PR, could a static subdomain be used?  For example:

hosting-project--pr0000-fix-issue-0000-stnczqi7.**prodjectid**.web.app

or even a static subdomain suffix, for example:

hosting-project--pr0000-fix-issue-0000-stnczqi7-**prodjectid**.web.app

This would help with configuring allowed hosts.

**Comment by jhuleatt** [comment]
@rthreei no, the preview URL will always have the form `SITE_NAME--CHANNEL_ID-RANDOM_HASH.web.app`. `CHANNEL_ID` is all that this action can control - the rest is set by the Hosting backend ([docs](https://firebase.google.com/docs/hosting/manage-hosting-resources#hosting-infrastructure)).

I'd suggest filing a feature request [here](https://firebase.google.com/support/troubleshooter/report/features) to ask that the Hosting backend support this.
