### ISSUE TITLE
I ma not able host my angular universal application in firebase

### ISSUE THREAD

**Issue by MUKESHBEHERA76** [FirebaseExtended/action-hosting-deploy#71]
Earlier I was able to host my Angular Universal app in firebase but after updating the firebase tool My latest version is getting uploaded successfully but no changes I can see on the website.
I am using
ng add @angular/fire then
ng deploy to deploy my application
Please help

**Comment by jhuleatt** [comment]
Hi @MUKESHBEHERA76, please [file a ticket with Firebase support](https://firebase.google.com/support#firebase-troubleshooter:~:text=Pick%20a%20category) to get help with this.
